### ISSUE TITLE
cannot convert ‘Z3_context {aka _Z3_context*}’ to ‘Z3_error_code’ for argument ‘1’ 

### ISSUE THREAD

**Issue by deepdarkfans** [mustakcsecuet/CFI-LB#10]
Hi, this error occurred during installation

`/root/autodl-tmp/CFI-LB/llvm-project/clang/lib/StaticAnalyzer/Core/Z3ConstraintManager.cpp: In function ‘void {anonymous}::Z3ErrorHandler(Z3_context, Z3_error_code)’:
/root/autodl-tmp/CFI-LB/llvm-project/clang/lib/StaticAnalyzer/Core/Z3ConstraintManager.cpp:48:71: error: cannot convert ‘Z3_context {aka _Z3_context*}’ to ‘Z3_error_code’ for argument ‘1’ to ‘const char* Z3_get_error_msg(Z3_error_code)’
                            llvm::Twine(Z3_get_error_msg(Context, Error)));`

`[ 98%] Built target clangStaticAnalyzerCheckers
[ 98%] Built target libclang
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2`

How do I solve it?

**Comment by mustakimur** [comment]
It is a dependency issue that we cannot resolve from the project side.
